### ISSUE TITLE
Enquiry about GSOC 2021

### ISSUE THREAD

**Issue by MaulikVarshney** [vipul79321/Google-Summer-of-Code-2020#1]
Hey Vipul, Is there any way I can contact you regarding your GSOC experience for the year 2020? It would be really helpful for me if you clear out a few doubts of mine. I am sorry, had to open an issue as I was unable to find your e-Mail id or any other way to contact you.

**Comment by vipul79321** [comment]
Hello maulik,
You can reach me out on linkedin or email me at 
vipul.gupta73921@gmail.com 
Also, Here is a link to my linkedin profile - 
https://www.linkedin.com/in/vipul-gupta-15a718161
